---
id: clear-code
tags:
- clear-code
version: 1.0.1
licenses:
- GPLv3+
- GFDL
- CC BY-SA 3.0
author:
  markup_language: :rd
  name: Kouhei Sutou
  email: kou@clear-code.com
  rubygems_user: kou
  slideshare_user: kou
  speaker_deck_user: 
