# Copyright (C) 2025  Sutou Kouhei <kou@clear-code.com>
#
# License: GPLv3+, GFDL and/or CC BY-SA 3.0
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

name: Release
on:
  push:
    tags:
      - "*"
jobs:
  github:
    name: GitHub
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          ruby \
            -e 'print("## "); puts(ARGF.read.split(/^## /)[1])' \
            NEWS.md > release-note.md
          title="$(head -n 1 release-note.md | sed -e 's/^## //')"
          tail -n +2 release-note.md > release-note-without-version.md
          gh release create \
            ${GITHUB_REF_NAME} \
            --discussion-category Announcements \
            --notes-file release-note-without-version.md \
            --title "${title}"

  rubygems:
    name: RubyGems
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      id-token: write
    environment: release
    steps:
      - uses: actions/checkout@v5
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby
      - name: Install dependencies
        run: |
          gem install rubygems-requirements-system
          gem install rabbit
      - uses: rubygems/configure-rubygems-credentials@v1.0.0
      - name: Push gems
        run: |
          rake publish:rubygems
